/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/ui/AppButton.vue')['default']
    AppButtonDelete: typeof import('./src/components/ui/AppButtonDelete.vue')['default']
    AppDataTable: typeof import('./src/components/data-table/AppDataTable.vue')['default']
    AppDocumentCard: typeof import('./src/components/documents-table/AppDocumentCard.vue')['default']
    AppDocumentsTable: typeof import('./src/components/documents-table/AppDocumentsTable.vue')['default']
    AppImageCard: typeof import('./src/components/image-table/AppImageCard.vue')['default']
    AppImageTable: typeof import('./src/components/image-table/AppImageTable.vue')['default']
    AppInputArrayField: typeof import('./src/components/inputs/AppInputArrayField.vue')['default']
    AppInputPasswordField: typeof import('./src/components/inputs/AppInputPasswordField.vue')['default']
    AppInputTextField: typeof import('./src/components/inputs/AppInputTextField.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    AppSimpleTableHeader: typeof import('./src/components/AppSimpleTableHeader.vue')['default']
    AppTablePagination: typeof import('./src/components/AppTablePagination.vue')['default']
    AppTextAreaField: typeof import('./src/components/inputs/AppTextAreaField.vue')['default']
    AppTopbar: typeof import('./src/components/topbar/AppTopbar.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataTableWrapper: typeof import('./src/components/data-table/components/DataTableWrapper.vue')['default']
    DocumentLink: typeof import('./src/components/DocumentLink.vue')['default']
    DocumentUpload: typeof import('./src/components/file-upload/DocumentUpload.vue')['default']
    EditPost: typeof import('./src/components/forms/EditPost.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormEditPost: typeof import('./src/components/forms/FormEditPost.vue')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    FormLogin: typeof import('./src/components/forms/FormLogin.vue')['default']
    FormNewDocument: typeof import('./src/components/forms/FormNewDocument.vue')['default']
    FormRegister: typeof import('./src/components/forms/FormRegister.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    ImageLink: typeof import('./src/components/ImageLink.vue')['default']
    ImageUpload: typeof import('./src/components/image-upload/ImageUpload.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MainImageUpload: typeof import('./src/components/image-upload/mainImageUpload.vue')['default']
    Message: typeof import('primevue/message')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('primevue/sidebar')['default']
    TableHeader: typeof import('./src/components/data-table/components/TableHeader.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
