/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBarChart: typeof import('./src/components/AppBarChart.vue')['default']
    AppDataTable: typeof import('./src/components/data-table/AppDataTable.vue')['default']
    AppDocumentsTable: typeof import('./src/components/documents-table/AppDocumentsTable.vue')['default']
    AppImageTable: typeof import('./src/components/image-table/AppImageTable.vue')['default']
    AppInputPasswordField: typeof import('./src/components/inputs/AppInputPasswordField.vue')['default']
    AppInputText: typeof import('./src/components/inputs/AppInputText.vue')['default']
    AppInputTextField: typeof import('./src/components/inputs/AppInputTextField.vue')['default']
    AppPieChart: typeof import('./src/components/AppPieChart.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    AppTopbar: typeof import('./src/components/topbar/AppTopbar.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Chart: typeof import('primevue/chart')['default']
    Column: typeof import('primevue/column')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataTableWrapper: typeof import('./src/components/data-table/components/DataTableWrapper.vue')['default']
    DocumentsTable: typeof import('./src/components/documents-table/DocumentsTable.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    Form: typeof import('@primevue/forms/form')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    Message: typeof import('primevue/message')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    Page: typeof import('./src/components/Page.vue')['default']
    Page404: typeof import('./src/components/Page404.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RegisterForm: typeof import('./src/components/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('primevue/sidebar')['default']
    TableHeader: typeof import('./src/components/data-table/components/TableHeader.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    UserForm: typeof import('./src/components/UserForm.vue')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
